import type { SpecExecAdapterContext } from "./context.ts";
import type { ExecutionMode } from "./execution-mode.ts";
import type { ParsedTask, ParsedTaskPlan } from "./task-plan-parser.ts";

export function buildSingleTaskPrompt(context: SpecExecAdapterContext, plan: ParsedTaskPlan, task: ParsedTask, mode: ExecutionMode): string {
  const completedSummary = plan.tasks
    .filter((entry) => entry.completed)
    .map((entry) => `- ${entry.id} ${entry.title} (${entry.kind})`)
    .join("\n") || "None.";

  const checkpointInstructions = task.kind === "checkpoint" ? `\nCheckpoint-specific instructions:\n- This checkpoint is a validation task, not a user approval gate.\n- Validate completed tasks in scope against requirements.md using concrete evidence.\n- If validation evidence does not satisfy requirements, return status \"blocked\" with blocker.type \"validation_failure\".\n` : "";

  return `You are a controlled task-executor child worker for Brainstorming Pro.\n\nYou are executing exactly one selected task from an approved tasks.md. Code owns task ordering, loop control, and checkbox updates.\n\nExecution mode: ${mode}\nTopic: ${context.topic}\nRun id: ${context.runId}\n\nCurrent task only:\n- id: ${task.id}\n- title: ${task.title}\n- kind: ${task.kind}\n- optional: ${task.optional ? "yes" : "no"}\n- requirement ids: ${task.requirementIds.join(", ") || "none"}\n- original line: ${task.originalLine}\n\nTask description and metadata:\n${task.descriptionLines.length ? task.descriptionLines.join("\n") : "None."}\n\nCompleted task summary (context only; do not execute or revise these tasks):\n${completedSummary}\n\nRequirements acceptance source of truth (requirements.md):\n\n${context.approvedRequirements.content}\n\n${context.approvedDesign ? `Background design context only (design.md; do not treat as acceptance truth):\n\n${context.approvedDesign.content}\n\n` : ""}Forbidden actions:\n- Do not execute later tasks.\n- Do not revise tasks.md or alter the approved plan.\n- Do not update tasks.md checkboxes or progress markers.\n- Do not modify approved requirements.md.\n- Do not modify approved design.md.\n- Do not perform destructive or irreversible operations. Return a structured blocker instead.\n- If blocked, return a structured blocker and stop.\n${checkpointInstructions}\nReturn only JSON matching this schema:\n{\n  \"kind\": \"single-task-result\",\n  \"taskId\": \"${task.id}\",\n  \"status\": \"completed\" | \"blocked\" | \"failed\",\n  \"changedFiles\": [\"relative/project/path.ts\"],\n  \"summary\": \"brief summary\",\n  \"validation\": {\n    \"commands\": [{ \"command\": \"npm test\", \"status\": \"passed\" | \"failed\" | \"not-run\", \"summary\": \"result summary\" }],\n    \"evidence\": [\"concrete evidence for completed work or checkpoint validation\"]\n  },\n  \"blocker\": {\n    \"task\": \"${task.id} ${task.title}\",\n    \"type\": \"conflict\" | \"underspecified\" | \"validation_failure\" | \"scope_change\" | \"destructive_op\" | \"missing_dependency\",\n    \"context\": { \"taskExcerpt\": \"...\", \"requirements\": \"...\" },\n    \"tried\": [\"what you tried\"],\n    \"risk\": \"why proceeding would violate the approved spec\",\n    \"options\": [\"option A\", \"option B\"],\n    \"neededFromUser\": \"minimum needed input\"\n  },\n  \"error\": { \"kind\": \"error-kind\", \"message\": \"message\", \"retryable\": false }\n}\n`;
}
